# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /flask-app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    libboost-all-dev \
    libgtk-3-dev \
    build-essential \
    cmake

# Update package list and install cmake
RUN apt-get update && apt-get install -y \
    cmake

# Install Python dependencies
COPY flask-app/requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

RUN pip install --upgrade pip

# Copy the rest of the application code
COPY . .

# Install additional Python packages
RUN pip3 install \
    scikit-learn \
    cmake \
    flask_cors \
    confluent_kafka

CMD python app.py
